spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

# MyBatis-Plus 配置
mybatis-plus:
  # 映射文件位置（如果后面写xml SQL用）
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名自动转换：数据库 create_time → 实体 createTime
    map-underscore-to-camel-case: true
    # 控制台打印执行 SQL（开发必备）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: deleted
      # 未删除值
      logic-not-delete-value: 0
      # 已删除值
      logic-delete-value: 1
      # 主键自增策略
      id-type: auto