spring:
  application:
    name: spring-study
  config:
    import: nacos:/spring-study-dev.yml
  profiles:
    active: dev # 激活环境

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  cloud:
    nacos:
      # Nacos 服务地址
      server-addr: 127.0.0.1:8848
      # 配置中心
      config:
        # 环境
        namespace: dev
        # 配置文件后缀，默认 properties，推荐 yml
        file-extension: yml
        # 分组（默认 DEFAULT_GROUP）
        group: DEFAULT_GROUP
      # 服务注册
      discovery:
        # 环境
        namespace: dev
        # 开启服务注册
        enabled: true
        # 分组
        group: DEFAULT_GROUP


# MyBatis-Plus 配置
mybatis-plus:
  # 映射文件位置（如果后面写xml SQL用）
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名自动转换：数据库 create_time → 实体 createTime
    map-underscore-to-camel-case: true
    # 控制台打印执行 SQL（开发必备）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: deleted
      # 未删除值
      logic-not-delete-value: 0
      # 已删除值
      logic-delete-value: 1
      # 主键自增策略
      id-type: auto